### ISSUE TITLE
PLNmodels is not compatible with R < 4.1

### ISSUE THREAD

**Issue by fplaza** [PLN-team/PLNmodels#124]
Hi @jchiquet ,

I have tried to install PLNmodels from the CRAN but it failed on R 3.6:
```
Error in parse(outFile) : 
  /tmp/RtmpUSHbgH/R.INSTALL1b016bcc75b7/PLNmodels/R/ZIPLN.R:96:143: '>' inattendu(e)
95:   covariance <- match.arg(covariance)
96:   if (covariance == "fixed") stopifnot("Omega must be provied for fixed covariance" = inherits(Omega, "matrix") | inherits(Omega, "Matrix")) |>
```
The pipe operator "|>" has been introduced in R 4.1. Contrary to what is stated in the CRAN, this new release is not compatible with R 3.X

**Comment by mahendra-mariadassou** [comment]
Hi @fplaza, 

Thanks for catching this, there were two instances of `|>` that went under my radar when I reviewed the code. A hotfix in the master branch will be up quickly and except this to be fixed in the next release.

**Comment by fplaza** [comment]
Hi @mahendra-mariadassou 
Thanks for the quick reply.
Meanwhile, I have installed the version 1.1.0
