### ISSUE TITLE
Bug in `PLNmixture()` when `clusters` is not a complete sequence

### ISSUE THREAD

**Issue by mahendra-mariadassou** [PLN-team/PLNmodels#95]
`PLNmixture()` with backward (and potentially forward) smoothing fails when the `clusters` argument is not a complete sequence starting at 1. 

```r
library(PLNmodels)
#> This is packages 'PLNmodels' version 0.11.7-9720
#> Use future::plan(multicore/multisession) to speed up PLNPCA/PLNmixture/stability_selection.
data(trichoptera)
trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)
myMixtures <- PLNmixture(Abundance ~ 1 + offset(log(Offset)), clusters = 2:4, data = trichoptera)
#> 
#>  Initialization...
#> 
#>  Adjusting 3 PLN mixture models.
#>  number of cluster = 2   number of cluster = 3   number of cluster = 4 
#> 
#>  Smoothing PLN mixture models.
#>    Going backward +
#> Error in self$models[[k]]: indice hors limites
```

<sup>Created on 2023-02-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The culprit are [here](https://github.com/PLN-team/PLNmodels/blob/bebbeccce2e8822767bba9cf840cba2118f3e889/R/PLNmixturefamily-class.R#L79) and [here](https://github.com/PLN-team/PLNmodels/blob/bebbeccce2e8822767bba9cf840cba2118f3e889/R/PLNmixturefamily-class.R#L82) as `k` refers both to the *number of clusters* and the *position* in the family of models.

**Comment by mahendra-mariadassou** [comment]
I realized while working on the fix that smoothing implicitly assumes that models in the family are *adjacent* (e.g. we have all models between 2 clusters and 10 clusters, not only the ones with 2, 5 and 10 clusters). I added a warning and easy fix but it might be useful to smooth with more spread out models. @jchiquet  I'll work on a fix in a separate and let you decide whether it's worth including in the package.

**Comment by jchiquet** [comment]
Could you please an entry in NEWS.md?

thanks!

**Comment by mahendra-mariadassou** [comment]
Done. And you can have a look at branch [mixture_smoothing](https://github.com/PLN-team/PLNmodels/tree/mixture_smoothing) to see how we can deal with _incomplete_ sequences (e.g. `c(1, 3, 5)`).
- Pros: Allows for arbitrary sequences and return the expected number of  models (one per requested number of clusters)
- Cons: Requires estimating (but not always returning) a mixture model for every `k` in `min(clusters):max(clusters)`. Wouldn't it be simpler to simply overwrite `clusters` with `min(clusters):max(clusters)` ?

**Comment by jchiquet** [comment]
This sounds good, and will match what the user has requested. Ok to merge in main/master for me.
Do you keep all the model fitted in memory or just use them for the browsing  during the slit/merge strategy ?

Thanks!

**Comment by mahendra-mariadassou** [comment]
I'll merge it. I keep only the requested models in memory, the others are only used during browsing.
