### ISSUE TITLE
dgCMatrix as an input

### ISSUE THREAD

**Issue by akhst7** [PLN-team/PLNmodels#96]
Hi, 

Is there any way to use a dgCMatrix without converting to matrix or data.frame  as an input for PLNPCA

**Comment by mahendra-mariadassou** [comment]
Hi, 

Sorry for the long delay in responding. There is currently no way to do this as we rely on `model.frame()` to provide a formula interface to the end-user. The simplest fix is to convert the dgCMatrix to a standard matrix as you do now.
